name: docker-ubuntu

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build tests homework1 hello_lib
      run: |
        cd hello_lib 
        docker build -t hello_world .
        
    - name: Run tests homework1 hello_lib
      run: |
        docker run hello_world
