name: docker-ubuntu

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build tests hello_world
        run: |
          cd hello_world
          docker build -t hello_world .

      - name: Run tests hello_world
        run: |
          docker run --rm hello_world

      - name: Build tests hello_lib
        run: |
          cd hello_lib 
          docker build -t hello_lib .

      - name: Run tests hello_lib
        run: |
          docker run --rm hello_lib

      - name: Build tests sdl_shared
        run: |
          cd sdl-shared
          docker build -t sdl_shared .

      - name: Run tests sdl_shared
        run: |
          docker run --rm sdl_shared

      - name: Build tests sdl_static
        run: |
          cd sdl-static
          docker build -t sdl_static .

      - name: Run tests sdl_static
        run: |
          docker run --rm sdl_static