name: mac_build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build tests homework1 hello_lib
      run: |
        cd hello_lib 
        mkdir build
        cd build
        cmake ..
        cmake --build .
