name: win

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build tests hello_world
      run: |
        cd hello_world
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
    
    - name: Run tests hello_world
      run: |
        cd hello_world/build
        ctest -C Release --output-on-failure

    - name: Build tests hello_lib
      run: |
        cd hello_lib 
        mkdir build
        cd build
        pip3 install conan
        conan profile detect
        conan install .. --build=missing --output-folder=. -s compiler.cppstd=20 -s compiler.runtime=static
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .

    - name: Run tests hello_lib
      run: |
        cd hello_lib/build/hello_lib
        ctest -C Release --output-on-failure
